### PR TITLE
Add less variables for Patternfly Color Palette colors

### PR DESCRIPTION
**Pull request by jeff-phillips-18**

### CODE REVIEW

**Comment by dtaylor113** [comment]
LGTM

**Comment by andresgalante** [comment]
@jeff-phillips-18 I think we should remove the color without number, since they are the same as `-400`.

**Comment by jeff-phillips-18** [comment]
@andresgalante I believe we want both so that we have the ability to modify if necessary.

**Comment by andresgalante** [comment]
@jeff-phillips-18 I don't agree, if we want to modify blue-400 then we modify it. duplicating them will only generate problems since if blue-400 changes blue will also have to change. Its not DRY.

**Comment by jeff-phillips-18** [comment]
@andresgalante OK, how about we change it to be
@color-pf-blue:  @color-pf-blue-400  ?

The point being we should have a standard blue.

**Comment by andresgalante** [comment]
@jeff-phillips-18 that is a better solution, but I wouldn't duplicate the names. Default is 400. I guess I am biased based on material design where default is 500, there is no default name without a saturation value.

**Comment by jeff-phillips-18** [comment]
@andresgalante Updated.

**Pull request merged**
