### PR TITLE
fix(skip link): position of button

### PR DESCRIPTION
**Pull request by matthewcarleton**
This fixes a bug where they fix link button was causing a scroll bar b/c it was positioned right instead of left.

### CODE REVIEW

**Comment by srambach** [comment]
Looks ok to me.

**Review by srambach — APPROVED** [review]
LGTM

**Comment by matthewcarleton** [comment]
great thanks @srambach :)

**Comment by jgiardino** [comment]
LGTM x 2

bitmoji

**Review by jgiardino — APPROVED** [review]

**Pull request merged**
