### PR TITLE
PTNFLY-1134 List View - Action Menu cut off by selected row

### PR DESCRIPTION
**Pull request by junezhang**
https://patternfly.atlassian.net/browse/PTNFLY-1134
Fixed issue #399 Popup in List View broken on specific selection
https://github.com/patternfly/patternfly/issues/399

Update files
less/lib/bootstrap/list-group.less

update the list-group-item.active z-index value

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
Updating bootstrap's list-group.less file won't works since that is copied from the bower installed version of bootstrap each time a build is done.

You need to over-ride the value in patternfly's list-group.less file

**Comment by junezhang** [comment]
@jeff-phillips-18 Thanks for kindly suggestion.
I updated the code in file list-group.less, not do any change to bootstrap's list-group.less.

@jeff-phillips-18  @srambach please help to check it. Thanks.

**Comment by jeff-phillips-18** [comment]
LGTM 👍

**Comment by srambach** [comment]
LGTM also.

**Pull request merged**
