### PR TITLE
Node security

### PR DESCRIPTION
**Pull request by priley86**
Adds [nsp](https://github.com/nodesecurity/nsp) to Travis CI pipeline.

### CODE REVIEW

**Comment by priley86** [comment]
@andresgalante @bleathem it looks nsp will work fine with our Travis build. You can see the security check has been added on our node modules in this build [here](https://travis-ci.org/patternfly/patternfly/builds/145036220)

```
$ ./node_modules/nsp/bin/nsp --shrinkwrap npm-shrinkwrap.json check --output summary
(+) No known vulnerabilities found
```

**Comment by bleathem** [comment]
The nsp addition looks great, however the PR seems to be conflated with https://github.com/patternfly/patternfly/pull/354.  Can we untangle the commits?

**Comment by priley86** [comment]
@bleathem done!

**Comment by andresgalante** [comment]
@priley86 thanks! as much as I can get the pipeline I think its right. But I'll let @bleathem merge it

**Comment by dlabrecq** [comment]
Can someone please fill me in? I don't see any conversations on IRC, Slack, etc.

I see Travis is shrink warpping npm-shrinkwrap.json, but don't understand why this is being done here? Is this just a check or are we creating a new shrinkwrap file? It doesn't appear to be checked into the repo?

Typically, npm is shrinkwraped as part of each release. If a different shrinkwrap is approach is required, please communicate that with the core members of the team -- I'd need to change some build scripts.

**Comment by priley86** [comment]
@dlabrecq this was a lesser discussed feature. It was in the [meeting notes](https://docs.google.com/document/d/1Qh0kWd4WcBbwgr8hX6Q4IV0sP7UO8bSgG_2lX9xe6uM/edit) and I think we mentioned it briefly in CI meeting.

It is a minor change - it will simply check our current npm-shrinkwrap.json dependencies for any vulnerabilities (doesn't create a new shrinkwrap). If you prefer a different security lib for this, maybe raise it as a suggestion? 

It looks like nsp has a pretty good list of consumers right now (see [#77](https://github.com/nodesecurity/nsp/issues/77)), but there are other options.

**Comment by andresgalante** [comment]
Just a little bit of  the story behind it. This comes from the 2 security issues we have from 2 dependencies that treeview consumes.

We have gemnasium to monitor the dependencies but it would be better if we could test PRs so we fix dependencies before we merge dependencies with security issues.

Introducing a bad dependency to PatternFly puts in risk every project that consumes and trust in PatternFly.

@abstractj , one of the security experts on Red Hat, pointed us to nsp.

**Comment by dlabrecq** [comment]
Thanks for the explanation. This will help with the release descriptions.

**Comment by priley86** [comment]
@andresgalante @dlabrecq @bleathem safe to merge? Wanted to check in and see if there is any other thoughts on merging this PR.

**Comment by dlabrecq** [comment]
Yes, my questions have been answered.

**Pull request merged**
