### PR TITLE
Require bootstrap v3.4.0 which resolves XSS

### PR DESCRIPTION
**Pull request by atodorov**
## Description

Require the latest bootstrap v3.4.0 which resolves a cross-site scripting vulnerability, see
https://github.com/twbs/bootstrap/releases/tag/v3.4.0

Note: can you review and release a new npm version for folks who would like to update ASAP ?

## Changes

* Update to bootstrap v3.4.0, resolves XSS vulnerability

## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [ ] **Cross browser**: works in IE11
- [ ] **Cross browser**: works in Edge
- [ ] **Cross browser**: works in Chrome
- [ ] **Cross browser**: works in Firefox
- [ ] **Cross browser**: works in Safari
- [ ] **Cross browser**: works in Opera
- [ ] **Responsive**: works in extra small, small, medium and large view ports.
- [ ] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

### CODE REVIEW

**Comment by atodorov** [comment]
@jeff-phillips-18, @mcoker please review

**Review by jeff-phillips-18 — DISMISSED** [review]

**Comment by atodorov** [comment]
anyone ping. Can we get this merged and a new minor version of patternfly released to npm so it pulls the latest bootstrap that deals with the XSS issue ?

**Comment by jeff-phillips-18** [comment]
Please set the commit message format correctly for release. Use `npm run commit` to guide you to the appropriate message.

**Review by mcoker — APPROVED** [review]
Looks good!

**Review by jeff-phillips-18 — APPROVED** [review]

**Comment by skateman** [comment]
Umm, this caused inconsitencies between the gem and the npm package :disappointed:

**Comment by atodorov** [comment]
See https://github.com/patternfly/patternfly/pull/1160

**Pull request merged**
