### PR TITLE
JSHint added, code style cleanup

### PR DESCRIPTION
**Pull request by akurdyukov**
I added some code style checks and formatted code a bit. Main problem was in `sidebar` variable that failed webpack to build a project with patternfly included.

### CODE REVIEW

**Comment by rhamilto** [comment]
Thanks, @akurdyukov!  This is a great addition!  Unfortunately, this change is "breaking" the js transformation of data tables.  See https://rawgit.com/akurdyukov/patternfly/master/tests/datatables.html vs. https://rawgit.com/patternfly/patternfly/master/tests/datatables.html  Mind taking a look?

**Comment by akurdyukov** [comment]
Sure. Bug is fixed now.

**Comment by rhamilto** [comment]
And one more, @akurdyukov.  Because sidebar() is no longer global, calling it via the data table call back [1] on https://rawgit.com/akurdyukov/patternfly/master/tests/tab.html no longer works.  

[1] https://github.com/akurdyukov/patternfly/blob/master/tests/tab.html#L588

**Comment by akurdyukov** [comment]
Alright, I fixed that, but now sidebar looks like jQuery plugin. It's the only effective global scope I have when loading with webpack. I really do not like putting anything into 'window'. What do you think?

**Comment by rhamilto** [comment]
Thank, @akurdyukov.  That seems reasonable to me.  

@erundle, @jeff-phillips-18, @dtaylor113, opinions?

**Comment by erundle** [comment]
Looks good to me!!!

**Comment by rhamilto** [comment]
Well, dang.  One more bug.  "PatternFly" [1] is no longer in the global scope.  Sorry I didn't catch that earlier.

[1] https://github.com/akurdyukov/patternfly/blob/master/tests/popovers.html#L93

**Comment by akurdyukov** [comment]
Updated :)

**Comment by rhamilto** [comment]
Thanks, @akurdyukov!  I made one additional commit to your PR as the test files are actually generated using Jekyll and the corresponding source test files (/tests-src/*.html) needed to be updated as well.

**Pull request merged**
