### PR TITLE
Fix the list-group-heading-overlap #324

### PR DESCRIPTION
**Pull request by jtomasek**

### CODE REVIEW

**Comment by andresgalante** [comment]
@jtomasek thanks for the PR. Can you please alphabetical order the declaration?

**Comment by andresgalante** [comment]
Hi @jtomasek, any news on this PR?

**Comment by jtomasek** [comment]
Updated, sorry for the delay

**Comment by andresgalante** [comment]
@jtomasek thanks a lot!!! 😄

**Comment by andresgalante** [comment]
@jtomasek Thanks a lot!!! 😄

**Pull request merged**
