### PR TITLE
Creates a PR template

### PR DESCRIPTION
**Pull request by andresgalante**
@priley86 @dlabrecq I've created this PR template to help get better PR descriptions and improve our for release notes.

What do you think?

### CODE REVIEW

**Comment by priley86** [comment]
bitmoji

I like this a lot - it will remind us to write better notes in PRs. 

Great idea on this!

**Comment by dlabrecq** [comment]
It would be incredibly helpful if folks provided better descriptions. When generating the release, we often have nothing except a couple words.

Unfortunately, I don't believe this would have captured @himdel's issues related to "will break any right floating toolbar" nor "will break toolbar spacing and separators". It's not clear that we knew that ourselves?

It would be good to discuss during the uxd/ui dev meeting and get consensus. Would like to know how all this will translate to release notes, how do we enforce it, etc.? 

I worry that a template may be overkill for some cases? For example, we made some simple script changes during the last release. I don't see the template being applicable for that (e.g., there is no rawgit). Perhaps we need an optional section to the template to cover more types of changes?

**Comment by andresgalante** [comment]
Great point Dan. Which parts would you ass to the template? And which ones would be optional?

**Comment by priley86** [comment]
👍  I'm ok with merging this template for now, and making adjustments as needed.

**Pull request merged**
