### PR TITLE
Adding dependencies for date-time-picker.

### PR DESCRIPTION
**Pull request by dlabrecq**

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
:+1:

**Comment by dtaylor113** [comment]
Hi, in package.json, eonasdan-bootstrap-datetimepicker should be version "4.15.35"  -there is no npm version "4.17.35"

**Comment by dtaylor113** [comment]
Looks like we'll have to also update https://github.com/patternfly/patternfly/blob/master/npm-shrinkwrap.json as well.  Still looking into the best way to do this.

**Comment by jeff-phillips-18** [comment]
Please run 'npm shrinkwrap' and include the newly generated npm-shrinkwrap.json

**Comment by dlabrecq** [comment]
Fixed eonasdan-bootstrap-datetimepicker version and regenerated npm-shrinkwrap

**Comment by dtaylor113** [comment]
LGTM

**Comment by dlabrecq** [comment]
Once this is merged, I'll start bumping the version number. Don't know if I can merge my own request or if someone else has to do that?

**Comment by jeff-phillips-18** [comment]
LGTM

**Pull request merged**
