### PR TITLE
Update jquery-match-height to 0.7.0

### PR DESCRIPTION
**Pull request by ceefour**

### CODE REVIEW

**Comment by dtaylor113** [comment]
LGTM

**Comment by jeff-phillips-18** [comment]
Should bower.json be updated as well?

**Comment by ceefour** [comment]
@jeff-phillips-18 done. hmm, the package name is different between bower and npm..

**Comment by jeff-phillips-18** [comment]
Yeah, I noticed that as well.
squash the commits and I will merge.

**Comment by ceefour** [comment]
@jeff-phillips-18 squashed

**Comment by jeff-phillips-18** [comment]
LGTM

**Pull request merged**
