### PR TITLE
fix(package.json): No default jsDelivr CDN file set

### PR DESCRIPTION
**Pull request by dabeng**
## Description
This PR is targeted to fix the [issue](https://github.com/patternfly/patternfly/issues/901)

## Changes
The following warning message will disappear:
screen shot 2018-01-16 at 2 19 46 pm

### CODE REVIEW

**Review by amarie401 — APPROVED** [review]

**Comment by LHinson** [comment]
@xeeljire will you review this one as well?

**Comment by cliffpyles** [comment]
Before we merge this one, I'd like to get a little more information about what problem the original issue was trying to solve. Since the project is primarily a CSS project (with a few exceptions), it seems like this change might not be appropriate for the goals of the project.

It could be a possibility in the future though. We will just need to put a little thought into the organization of the JS. We don't currently offer the JS assets as ES6 modules. @dgutride @jeff-phillips-18 @priley86 What are your thoughts on this?

**Comment by priley86** [comment]
@cliffpyles i hope i am not conflating this issue... however one thing that has come up in the past is we'd love to be able to consume PF settings/globals as ES6 modules instead of globals. This came in pf-react recently here:

https://github.com/patternfly/patternfly-react/blob/master/src/common/patternfly.js

i.e. instead of saying:
```
import 'patternfly/dist/js/patternfly-settings';
import 'patternfly/dist/js/patternfly-settings-charts';

const patternfly = window.patternfly;
const c3ChartDefaults = patternfly.c3ChartDefaults();
```
it might be nice to also expose an ES6 Module in PF Core (so something like this would be supported) :
```
import {pfBreakpoints, c3ChartDefaults, ... } from 'patternfly';
```
Not sure if this is possible yet - have not looked into it. Icing on the cake here would also be adding the `mobile: 0` breakpoint:
https://github.com/patternfly/patternfly-react/pull/88#pullrequestreview-89568402

cc: @jeff-phillips-18 @mturley

**Comment by cliffpyles** [comment]
@priley86 Yeah, I agree. ES6 modules would be awesome! I'm wondering about level of effort and scope of this PR though. @LHinson I'll add a ticket to the backlog to investigate. Any objections?

**Comment by amarie401** [comment]
I agree with you both. I think introducing ES6 modules would be a great move. @cliffpyles should we hold off then on this merge?

**Comment by LHinson** [comment]
that sounds good @cliffpyles - we can point it monday at grooming.

**Comment by dabeng** [comment]
Hi @priley86 @cliffpyles . You are right. It's better to hold off this PR until we refactor the patternfly-core according to ES6 module specification. You know that current patternfly.js is a set of jquery plugin settings. It will be a huge task.

**Comment by jeff-phillips-18** [comment]
@dabeng Should this be closed at this point?

**Comment by LHinson** [comment]
Yes, I'll go ahead and close. Thanks.

**Pull request closed without merging**
