### PR TITLE
Updated readme and quick start to reflect dependency install locations

### PR DESCRIPTION
**Pull request by dlabrecq**
## Description
Updated readme and quick start to reflect dependency install locations when npm 3 and shrink wrap are used.

The npm install of patternfly 3.16.0 includes a shrinkwrap file; thus, npm 3 installs dependencies are installed under the node_modules/patternfly/node_modules directory. Previous versions v3.0.0 - v3.9.0 also included this shrinkwrap file and those dependencies were installed under the same directory as well. For some reason, the npm install for versions v3.10.0 - v3.15.0 omitted the shrinkwrap file (even though it was properly committed), so dependencies for those versions inadvertently install at the root node_modules directory.

If users prefer a flat dependency structure, they can define their own dependencies explicitly. That will flatten out the node_modules structure and place dependencies in the root node_modules directory.

## Changes

Updated readme and quick start to reflect proper dependency install locations.

### CODE REVIEW

**Comment by dlabrecq** [comment]
@bleathem I'd like to merge this so the docs reflect the proper directory structure.

**Comment by dlabrecq** [comment]
Last chance?

**Review by dgutride — APPROVED** [review]

**Comment by andresgalante** [comment]
@priley86 @bleathem this is a simple change, it should be easy to review.

**Review by jeff-phillips-18 — APPROVED** [review]
👍

**Comment by priley86** [comment]
looks great to me @dlabrecq. thanks for tackling this and flattening our dependency tree.

**Review by bleathem — COMMENTED** [review]
Looks good, thanks Dan!

**Pull request merged**
