### PR TITLE
fix(filter): Use Datatables column().search() API to allow to filter ajax data

### LINKED ISSUE #670: Datatable filter with Ajax data source
I am using the table view with the pfFilter extension. My data is sourced via an ajax call and filtered on the server via DataTables's server side rendering. DataTables handles filtering in this case by setting headers on the request.

Is it possible to make patternfly filters set these headers?

### PR DESCRIPTION
**Pull request by tuxgasy**
## Description
Call Datatables column().search() API before redraw the table.

Fixes: https://github.com/patternfly/patternfly/issues/670

### CODE REVIEW

**Review by dlabrecq — DISMISSED** [review]
I built and ran the source locally. Filtering seems to work fine with these changes. It still filters client-side data by lowercase.

Update: need to retest latest changes

**Comment by jeff-phillips-18** [comment]
Please squash commits and use semantic release commit formatting: https://github.com/patternfly/patternfly#git-commit-guidelines

**Comment by andresgalante** [comment]
Hi @jeff-phillips-18 when you have a min, can you please check if we can merge this one?

**Comment by jeff-phillips-18** [comment]
nit: Can we change the commit (and PR title) to Datatable rather than filter?

**Comment by AdamJ** [comment]
@jeff-phillips-18 can this PR be merged, or does the commit message need to be altered?

**Comment by jeff-phillips-18** [comment]
we could alter the commit message on merge once this is approved if @tuxgasy does not update it.

**Comment by dlabrecq** [comment]
I retested the latest changes an there appears to be something wrong. I recall the first iteration of this PR worked when tested, but the commits have been squashed and don't remember why it changed?

The table examples are not showing any rows in the test pages.
screen shot 2018-04-30 at 10 20 03 am

**Review by dlabrecq — CHANGES_REQUESTED** [review]
I retested the latest changes an there appears to be something wrong. 

I recall the first iteration of this PR worked when tested, but the commits have been squashed and don't remember why it changed?

The table examples are not showing any rows in the test pages.
screen shot 2018-04-30 at 10 20 03 am

**Comment by tuxgasy** [comment]
I realized that my PR did not solve the problem completely. If I apply filters on multiple columns, only the last filter is send to the server.

Sorry for my late response!

**Comment by LHinson** [comment]
No worries @tuxgasy. Things get busy! Should I close this PR for now or do you expect to send more updates to address the issue?

**Comment by tuxgasy** [comment]
I do not know how to implement this properly. So I think we can close this PR!

**Comment by LHinson** [comment]
ok thanks for getting back to me @tuxgasy

**Pull request closed without merging**
