### PR TITLE
fix JS scope in examples

### PR DESCRIPTION
**Pull request by michpetrov**
Limited the scope of JavaScript in several examples, i.e. when included on a page the accompanying script will only apply to the given example and will not affect the rest of the page or other examples.

(Omitted the template since this is not a design change)

### CODE REVIEW

**Comment by bleathem** [comment]
@michpetrov is this change resolving any observable bugs/issues?

**Comment by michpetrov** [comment]
I thought I included it in the commit message - the associated issue is #641, one reported bug is patternfly/patternfly-org#408 but I figured I'll fix other potential problems.

**Comment by andresgalante** [comment]
Closes #641

**Comment by amarie401** [comment]
@michpetrov could you resolve the conflicting files in this PR?

**Comment by michpetrov** [comment]
@amarie401 I've rebased the PR

**Review by amarie401 — APPROVED** [review]

**Comment by cliffpyles** [comment]
Thanks for the contribution! Would you mind breaking these changes into individual PRs? When each PR is scoped to one bug, it allows us verify the changes in a more thorough manner. This also minimizes the risk of introducing new bugs.

**Review by amarie401 — COMMENTED** [review]
We might need to break down the scope of this PR in order to review these changes more thoroughly.

**Review by cliffpyles — COMMENTED** [review]
Thanks for the contribution! Would you mind breaking these changes into individual PRs? When each PR is scoped to one bug, it allows us verify the changes in a more thorough manner. This also minimizes the risk of introducing new bugs.

**Comment by michpetrov** [comment]
I'll get to it, but it won't be this week.

**Pull request closed without merging**
