### PR TITLE
Adding additional actions to toolbar

### PR DESCRIPTION
**Pull request by rhamilto**
Important:  these changes are not backward compatible with the existing
toolbar markup!

### CODE REVIEW

**Comment by rhamilto** [comment]
@andresgalante, please review.  I had to make some backward-incompatible markup changes to make the layout work with the new additions.  What do you think?

**Comment by jeff-phillips-18** [comment]
Any plans to add Simple Sort to this as well?

Edit:  I see it now. Sorry.

**Comment by andresgalante** [comment]
:+1:  sorry, I should have though of the new components when I build it.

**Comment by jeff-phillips-18** [comment]
LGTM

**Comment by rhamilto** [comment]
@andresgalante, no worries.  I don't think anyone besides @jeff-phillips-18 is using the toolbar yet, so it shouldn't be too much of an issue.  Assuming you're good with the changes, please merge, @andresgalante?

**Pull request merged**
