### PR TITLE
[*WIP*] JQuery Components Showcase

### PR DESCRIPTION
**Pull request by amarie401**
## Description
Set of initial JQuery components for showcase page. 

## Changes
Integrated Handlebars.js for templating using script created by @bleathem 

jquery-showcase

## To View
- pull jquery-showcase remote branch
- run 'npm install'
- run 'npm run jquery-dev'

## Todo
- [ ] Set up Travis config to build jQuery pages (no rawgit currently available)
- [ ] Make sure all components are responsive in medium/small viewports
- [ ] Add any missing components to showcase
- [x] Rebase commits

## PR checklist (if relevant)

- [X] **Cross browser**: works in Chrome
- [ ] **Responsive**: works in extra small, small, medium and large view ports.
- [X] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

@jeff-phillips-18 @andresgalante

### CODE REVIEW

**Comment by bleathem** [comment]
This looks great for an initial start!

**Comment by jeff-phillips-18** [comment]
When did this go non-WIP?

**Comment by amarie401** [comment]
From my knowledge it is still WIP @jeff-phillips-18, I believe it is just being merged into a jquery-showcase branch in PF while I continue to update and make changes. @bleathem can you elaborate on this?

**Comment by jeff-phillips-18** [comment]
@amarie401 OK, thanks. I didn't see the branch being merged to.

**Comment by amarie401** [comment]
No problem!

**Pull request merged**
