### PR TITLE
Update readme to be more clearly separate the instructions

### PR DESCRIPTION
**Pull request by dgutride**
I rewrote the development instructions a bit to hopefully make the distinction between what a consumer and what a developer would do.

@LHinson @mindreeper2420

### CODE REVIEW

**Comment by bleathem** [comment]
I like the improved clarity.

+1

**Comment by LHinson** [comment]
Awesome! Thanks @dgutride

**Comment by srambach** [comment]
LGTM. Much clearer.

**Comment by AdamJ** [comment]
Looks good. Thanks for updating this!

**Comment by jeff-phillips-18** [comment]
LGTM

**Pull request merged**
