### PR TITLE
Fixing issue that makes horizontal nav items disappear in mobile viewport

### PR DESCRIPTION
**Pull request by cardosogabriel**
## Description
This PR fixes the issue that makes horizontal nav items of the Vertical Nav type disappear in mobile viewport and makes them collapse under the hamburger menu. To do that, the HTML structure was required to change, following a structure more similar to the horizontal nav implementation. 
Since there was no design for the icons under the hamburger, I'm proposing a design following our design style.

Jira story: https://patternfly.atlassian.net/browse/PTNFLY-1934

## Changes
* Moved the items that where disappearing, including the Notification Drawer, from under <nav class="navbar navbar-pf-vertical"> to <nav class="nav-pf-vertical">. This ensure that they collapse under the hamburger menu.
* Adjusted class structures and attributes to make the icons and notification drawer work properly and look good in all viewports. 
* Made the icon "new window" persist at the top nav even on mobile view. To allow that, the HTML changed a bit and the variable @navbar-pf-vertical-navbar-brand-name-breakpoint was updated.
* Created the mixin .dropdown-menu-nav-mobile. These styles have been used for the horizontal nav mobile viewport, and the same styles are now being used for the vertical nav mobile viewport, so I created the mixin to avoid duplicated code. 
* Deleted the widget nav-vertical-notification-drawer.html since it is no longer used.
* Fixed the bug that makes the Notification Drawer have small width when expanded in mobile view.
* Supported the infotip dropdown for Alerts in the vertical nav mobile.

## Images
Vertical Nav Mobile
Vertical Nav Mobile - Notification Drawer
Vertical Nav Mobile - Notification Drawer Expanded
Vertical Nav Mobile - Alerts open
Vertical Nav Mobile - Dropdown open
Horizontal Nav Mobile - Notification Drawer Expanded

## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [ ] **Cross browser**: works in IE11
- [ ] **Cross browser**: works in Edge
- [X] **Cross browser**: works in Chrome
- [X] **Cross browser**: works in Firefox
- [X] **Cross browser**: works in Safari
- [X] **Cross browser**: works in Opera
- [X] **Responsive**: works in extra small, small, medium and large view ports.
- [X] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

### CODE REVIEW

**Comment by andresgalante** [comment]
@cardosogabriel the fact that the icons have no labels is affecting the way it look. I think we should add labels on small devices.

**Comment by cardosogabriel** [comment]
@andresgalante I'm ok the way it is, but also ok to add labels.
@LHinson , would this be a definition from visual design?

**Comment by cardosogabriel** [comment]
@andresgalante , updated the design adding labels, as you requested. Please check.

**Comment by serenamarie125** [comment]
@cardosogabriel @andresgalante, I would think that the items that are on the application banner would fall below the items that already exist on vertical primary navigation.  @LHinson do we have a design that this is already following?  I think that @beanh66 has some design work somewhere around this.

**Comment by beanh66** [comment]
@andresgalante @serenamarie125 Agreed, I described the order of items from the application banner when I put up the Masthead pattern. I had these items underneath the main navigation items. You can check out the PR documentation [here](https://github.com/beanh66/patternfly-design/blob/e54ca289496a3d13d35f4272ddb02c9fb7ad7ada/pattern-library/application-framework/masthead/masthead_design.md#general-considerations) under the section labeled Hamburger Menu.

**Comment by andresgalante** [comment]
@serenamarie125 you are right,I think Gabriel was following the way we have it on the horizontal nav. Maybe we can change both.

**Comment by serenamarie125** [comment]
@andresgalante I'd suggest that we have a proposed design that we agree on before this is reworked & merged

**Comment by LHinson** [comment]
Open design question: What happens to the dropdown in the responsive state? Should the arrows be there?

**Comment by jennyhaines** [comment]
@andresgalante @cardosogabriel @serenamarie125 Hello group! I'm going to create the visual design around this new mobile-friendly vertical nav, and will get started on that today. My first inclination is also to drop the items that were once in the masthead down to fall below the main navigational items, as they seem to be of secondary importance in relationship to the main nav items. (same as what @beanh66 had specified in her PR documentation) 

It will also be nice to differentiate this grouping a little more in terms of sizing so that the hierarchy of everything in the nav is very apparent. Currently the main nav items and the rest of the items are looking too similar- there should be an obvious difference in styles.

@LHinson - to answer your design question, there are multiple ways we can approach this, and I'll mock those up.

**Comment by jennyhaines** [comment]
@LHinson @andresgalante @cardosogabriel @serenamarie125 @beanh66

Before I create a separate PR to add in the new vertical nav design to PatternFly, I'm curious what the group thinks about these designs I've mocked up for adding the masthead items to the vertical nav at small screen sizes.

**Comment by jennyhaines** [comment]
verticalnav-responsive

verticalnav-notifications-responsive

verticalnav-alerts-responsive

verticalnav-help-responsive

**Comment by andresgalante** [comment]
Continues in #615

**Pull request closed without merging**
