### PR TITLE
Split the jquery plugins into individual files

### PR DESCRIPTION
**Pull request by dlabrecq**
## Description
Broke apart the patternfly-jquery javascript file into multiple files, one per plugin, and introduced a build step to provide the original combined file.

PTNFLY-2050 Split the jquery plugins into individual files

## Changes

Split JS code from 'src/js/patternfly-settings.js' and 'src/js/patternfly-functions.js' to:

- 'src/js/patternfly-settings-colors.js',
- 'src/js/patternfly-settings-charts.js',
- 'src/js/patternfly-functions-sidebar.js',
- 'src/js/patternfly-functions-popovers.js',
- 'src/js/patternfly-functions-data-tables.js',
- 'src/js/patternfly-functions-navigation.js',
- 'src/js/patternfly-functions-count-chars.js',
- 'src/js/patternfly-functions-colors.js',
- 'src/js/patternfly-functions-charts.js',
- 'src/js/patternfly-functions-fixed-heights.js',
- 'src/js/patternfly-functions-tree-grid.js',
- 'src/js/patternfly-functions-vertical-nav.js'

## Link to rawgit and/or image

https://rawgit.com/dlabrecq/patternfly/PTNFLY-2050-dist/dist/tests/

## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [ ] **Cross browser**: works in IE11
- [ ] **Cross browser**: works in Edge
- [ x] **Cross browser**: works in Chrome
- [ x] **Cross browser**: works in Firefox
- [ ] **Cross browser**: works in Safari
- [ ] **Cross browser**: works in Opera
- [ ] **Responsive**: works in extra small, small, medium and large view ports.
- [ ] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
Would this be better left for the Patternfly 4 release? I assume Patternfly will bump to 4.0 when Angular Patternfly bumps to 4.0.

**Review by dtaylor113 — APPROVED** [review]

**Comment by dlabrecq** [comment]
@jeff-phillips-18 The 4.0 question may be best answered by @bleathem? Brian is moving the test pages, unit tests, etc. to a new repo. I assume that will be 4.0, but not yet available.

Note that we split the patternfly.js file into patternfly-settings.js and patternfly-functions.js for v3.13.0 (I believe). The new files are concatenated in the same order, so there is essentially no change to patternfly.js.

**Comment by dlabrecq** [comment]
I spoke with Brian and created a branch-4.0-dev branch for Patternfly. I've changed the base for this PR to merge there instead.

**Comment by bleathem** [comment]
This change looks good to me.  It's easier to understand where to find the relevant component code in the broken out file structure.

:+1: merge

**Review by bleathem — APPROVED** [review]

**Review by jeff-phillips-18 — APPROVED** [review]
👍

**Pull request merged**
