### PR TITLE
Move tests and tests-src

### PR DESCRIPTION
**Pull request by priley86**
*Moves tests-src -> tests
*moves tests -> dist/tests
*updates gruntfile

### CODE REVIEW

**Comment by priley86** [comment]
will rebase #342 after merge

**Comment by dtaylor113** [comment]
Tested 'grunt server', 'grunt build', and livereload.  Source files seem to be in correct directories. 
LGTM  -nice job :+1:

**Comment by priley86** [comment]
@dtaylor113 thanks!

**Comment by dtaylor113** [comment]
@priley86  Once this PR is merged, please update the jira story and indicate the test-src task has been completed.  Extra credit if you cross-ref this PR# in the Jira story :smile:  

PatternFly base ref. GitHub repo. source code re-org - Dev
https://patternfly.atlassian.net/browse/PTNFLY-1576

**Comment by priley86** [comment]
PTNFLY-1576 #comment moves test and test-src

**Pull request merged**
