### PR TITLE
fix(toolbar): Update alignment of the 'x' in the toolbar filter

### LINKED ISSUE #989: The vertical alignment of "x" in the filter chips in the PatternFly toolbar is off
When looking at the [PF Test Page for Toolbar](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/toolbar.html) you can see that the "x" is not vertically aligned appropriately.

Both @kybaker and @jennyhaines confirmed that there is a visual issue here, and can provide input if necessary.

I'm not sure if the filter chip is a label with a close button? 

Here's a screenshot of the test page implementation:
screen shot 2018-03-14 at 10 12 10 am

### PR DESCRIPTION
**Pull request by AdamJ**
## Description
Update the alignment of the 'x' in the toolbar filter label to be vertically aligned with the span and not the text.

fixes https://github.com/patternfly/patternfly/issues/989

## Changes

Update vertical alignment of the 'x' in the toolbar filter label.

* Set the `<a>` within the `<span>` to be `vertical-align: middle`

**Old**
screen shot 2018-04-22 at 2 05 16 pm

**New**
screen shot 2018-04-22 at 2 05 38 pm

https://rawgit.com/mindreeper2420/patternfly/issue-989-dist/dist/tests/toolbar.html

## PR checklist (if relevant)

- [X] **Cross browser**: works in IE9
- [X] **Cross browser**: works in IE10
- [X] **Cross browser**: works in IE11
- [X] **Cross browser**: works in Edge
- [X] **Cross browser**: works in Chrome
- [X] **Cross browser**: works in Firefox
- [X] **Cross browser**: works in Safari
- [X] **Cross browser**: works in Opera
- [X] **Responsive**: works in extra small, small, medium and large view ports.
- [X] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

### CODE REVIEW

**Comment by matthewcarleton** [comment]
@mindreeper2420 can you provide the rawgit link for this?

**Comment by AdamJ** [comment]
@matthewcarleton what is the best way to use rawgit on a PR branch with no `dist` folder?

**Comment by matthewcarleton** [comment]
@mindreeper2420 Travis should be providing the branch with the dist but I see your build failed so we should figure out what's going on there. @dgutride probably has a solution for this.

**Comment by AdamJ** [comment]
@matthewcarleton so the build was successful here, but not on my repo's branch, so no `dist` folder was created. I'm going to try to figure out the build script bug today.

**Comment by AdamJ** [comment]
@matthewcarleton here is the rawgit link: https://rawgit.com/mindreeper2420/patternfly/issue-989-dist/dist/tests/index.html

**Comment by matthewcarleton** [comment]
thanks @mindreeper2420 it looks like it's still off by two pixels :( that's in safari have you tested in other browsers with different results?

**Comment by AdamJ** [comment]
@matthewcarleton I tested in Chrome, Firefox and Safari, as well as the others. I'm running Chrome v66, Firefox v59, Safari on High Sierra and virtual machines for MS browsers (I don't use browserstack). It could be that I had a zoom in place or something else that threw it off? I'll verify.

**Comment by AdamJ** [comment]
@matthewcarleton what version of Safari/macOS did you notice the 2px difference on? I'm using Safari 11.1 w/macOS 10.13.4, and I'm not seeing any shift.

Looks good on Firefox 60 and Chrome 66 too.

**Comment by matthewcarleton** [comment]
hmmm strange. This is what I see:
Chrome 66
Chrome 66
Safari 11 osX 10.13.2
screen shot 2018-05-16 at 2 51 31 pm
Firefox 60
screen shot 2018-05-16 at 2 57 50 pm

and just to confirm I am looking at https://rawgit.com/mindreeper2420/patternfly/issue-989-dist/dist/tests/toolbar.html

**Comment by matthewcarleton** [comment]
Success!

**Comment by AdamJ** [comment]
@matthewcarleton I've updated the PR to swap out the `pficon-close` with `fa-times`. This looks to have fixed the alignment, without needing any additional CSS.

**Review by matthewcarleton — APPROVED** [review]
thanks for figuring it out Adam! Nice work 👍

**Comment by jeff-phillips-18** [comment]
This doesn't really help any current uses of the toolbar. No one will know they need to replace the `pficon pficon-close` with `fa fa-times` in their html.

**Comment by LHinson** [comment]
@jeff-phillips-18 @mindreeper2420 will this break current users? If not, let's merge this and communicate out about the update and include in release notes since it's an improvement to what we have now.

**Comment by AdamJ** [comment]
This will not break any current users. As the CSS hasn't changed, anyone who is currently using the PatternFly icon will not be affected. It will only make a difference for those that start to use the toolbar after this is merged, or those who reference the code examples.

**Review by LHinson — APPROVED** [review]

**Review by dgutride — APPROVED** [review]

**Comment by LHinson** [comment]
@serenamarie125 wanted to give you a heads up on this one since you filed the issue. This latest update will fix the alignment issue however it requires an extra step on the consumer side to swap out the icon to see the change.

**Pull request merged**
