### PR TITLE
chore(commits): Implemented commitizien to help format commit messages

### PR DESCRIPTION
**Pull request by bleathem**
Installed and configured commitizen to help format commit messages.  Can be invoked using "npm run
commit"

### CODE REVIEW

**Comment by dtaylor113** [comment]
Hi @bleathem, would it be possible to add a screenshot and/or text of what these additions do?  -thanks

**Comment by bleathem** [comment]
@dtaylor113 the commitizen README shows well what the interaction looks like:
https://github.com/commitizen/cz-cli

I encourage you to checkout this branch, add a change, then run "npm run commit" to try it out.  (You can discard the commit afterwards without pushing)

**Comment by bleathem** [comment]
@dtaylor113 also I've (just now) updated the README with usage instructions and links ot the commitizen docs.

**Review by dtaylor113 — APPROVED** [review]
Thanks, LGTM

**Review by jeff-phillips-18 — APPROVED** [review]

**Comment by bleathem** [comment]
Further README updates in this PR:
https://github.com/patternfly/patternfly/pull/740

**Pull request merged**
