### PR TITLE
resolving conflicts on previous commit

### PR DESCRIPTION
**Pull request by jgiardino**
## Description

This is a minor update to the previous wizard updates in https://github.com/patternfly/patternfly/pull/474/files

Jira story: https://patternfly.atlassian.net/browse/PTNFLY-1827
## Changes
- included javascript to ignore disabled Back button on first screen

### CODE REVIEW

**Comment by LHinson** [comment]
@andresgalante @cardosogabriel need help reviewing this one

**Comment by andresgalante** [comment]
@bleathem @priley86 @dlabrecq Can guys guys review and merge this PR? 

I've checked the CSS on #474  and it looks great, thanks @jgiardino 👍

**Comment by jeff-phillips-18** [comment]
👍

**Comment by andresgalante** [comment]
Thanks @jeff-phillips-18 😄

**Pull request merged**
