### PR TITLE
Adding the ability to have a tooltip on negative space of progress bar

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by rhamilto** [comment]
@andresgalante, @erundle review and merge, please?  This ability will be leveraged in the forthcoming utilization bar card, which utilizes progress bars.

**Comment by andresgalante** [comment]
:+1:

**Comment by rhamilto** [comment]
I found a bug.  Hold please.

**Comment by rhamilto** [comment]
Bug fixed.  Resume review and merge.

**Comment by erundle** [comment]
LGTM. Please rebase and I will merge

**Pull request merged**
