### PR TITLE
Adding utilization bar card and supporting elements

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by dtaylor113** [comment]
LGTM

**Comment by rhamilto** [comment]
@andresgalante, can you review and merge?  @erundle is at a conference for a couple days, and I'd prefer this not wait until Wed.

**Comment by andresgalante** [comment]
@rhamilto is this an issue?
Image of card

**Comment by erundle** [comment]
@rhamilto the code looks fine but the label widths seem too small IMO. Was this approved by design?

**Comment by erundle** [comment]
screen shot 2015-10-19 at 10 30 11 am

**Comment by rhamilto** [comment]
> @rhamilto the code looks fine but the label widths seem too small IMO. Was this approved by design?

yes, it was.  it's actually roughly 10px wider than @kybaker's mock.

**Comment by dtaylor113** [comment]
HI, what is the status of this PR, what are we waiting on?  -thanks

**Comment by andresgalante** [comment]
@dtaylor113 if @kybaker is ok with the overlapping text on the cards, go ahead and merge it

**Comment by erundle** [comment]
@andresgalante I don't think that is from this PR. If we consider it an issue I am going to suggest we open up an issue for it.

**Pull request merged**
