### PR TITLE
Bump bootstrap-sass gem to 3.4.0

### PR DESCRIPTION
**Pull request by daslicious**
Resolves XSS vulnerability

## Description
Resolves XSS vulnerability for patternfly-sass gem.

(optional) Include related PRs, Issues and or Jira stories.
https://github.com/patternfly/patternfly/pull/1157/

## Changes

Write a list of changes the PR introduces

Updates bootstrap-sass

## Link to rawgit and/or image

N/A

## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [ ] **Cross browser**: works in IE11
- [ ] **Cross browser**: works in Edge
- [ ] **Cross browser**: works in Chrome
- [ ] **Cross browser**: works in Firefox
- [ ] **Cross browser**: works in Safari
- [ ] **Cross browser**: works in Opera
- [ ] **Responsive**: works in extra small, small, medium and large view ports.
- [ ] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

### CODE REVIEW

**Review by jeff-phillips-18 — APPROVED** [review]

**Comment by jeff-phillips-18** [comment]
Please use `npm run commit` to correctly format the commit message for release.

**Comment by daslicious** [comment]
does this need to be redone so there's just 1 commit with the right message?

**Comment by jeff-phillips-18** [comment]
It can be fixed by the merge-er

**Comment by skateman** [comment]
You will also have to push a new version due to this, because the gem is already available and of course inconsistent with the NPM package :disappointed:

**Comment by atodorov** [comment]
Also see https://github.com/patternfly/patternfly/pull/1160 before pushing a new version.

**Comment by skateman** [comment]
@jeff-phillips-18 and what about this one?

**Comment by skateman** [comment]
Thanks!

**Comment by skateman** [comment]
@jeff-phillips-18 can you push a new release so we can actually consume these XSS fixes?

**Comment by jeff-phillips-18** [comment]
This _should_ create a bug fix release as I modified the commit message

**Pull request merged**
