### PR TITLE
addition of typescript files

### PR DESCRIPTION
**Pull request by Layla-P**
## Description
A definition type file has been created for patternfly.js

## Changes
All new files

attn:
@bleathem

### CODE REVIEW

**Comment by bleathem** [comment]
This is great, thanks for the contribution @Layla-P!  The typings are a good fit for this repo, as they will then be available for all consuming repos.

However the typescript api code introduced is not a good fit, as it doesn't reflect the programming model currently used in this repo.  

Could you please remove the APIs and include only the typescript typings in this PR?

**Comment by Layla-P** [comment]
Hey @bleathem I have removed the files as requested.  Are you happy with the typings files I have included?  Or would you just like the patternfly one?

**Comment by bleathem** [comment]
Thanks @Layla-P.  That's an interesting question, let's see what our community has to say.

@dgutride @dlabrecq @priley86 thoughts on the ts typing contribution from @Layla-P?

**Comment by dlabrecq** [comment]
I looked through the typescript definitions and there is a lot here. The definitions in patternfly.d.ts look like something we could pull into Patternfly because it's based on our scripts. I'm not sure about the definitions for jQuery, C3, D3, Datatables, and Bootstrap?

**Comment by Layla-P** [comment]
@dlabrecq I have written several typescript api's which make use of the type definitions such as a charting api.  However, Brian asked me not to include them as he thought them not to be generic enough.
If the definitions aren't of use to you, that's no issue what so ever, I just thought I would share them and save someone the bother I've writing them as I have.
I have also written documentation on using the api's.

**Comment by dlabrecq** [comment]
Can you please share the documentation? That would be very helpful. Thanks!

**Comment by Layla-P** [comment]
@dlabrecq I have emailed you on your redhat email.

**Comment by dlabrecq** [comment]
Thank you for passing that along. It's very interesting to see how you're using the API. Is it ok to share your link internally with the Patternfly team (Brian, Patrick, Dana, etc.)?

**Comment by bleathem** [comment]
Thanks again for the contribution @Layla-P.  I discussed this PR with @dlabrecq and @jeff-phillips-18.  While we feel the typings overall would be very useful for someone building there application with patternfly, the non-pattternfly typings would be better suited for a library like https://github.com/DefinitelyTyped/DefinitelyTyped.

The patternfly typing is however something that makes sense for use to host.  Would you mind updating this PR to include only the patternfly typings file?

**Comment by bleathem** [comment]
I added a commit to this PR removing the non-jquery typings.  I will next send an e-mail to patternfly-list to kickstart a discussion around whether or not the community would find the inclusion of this typings file to be a valuable addition to patternfly.

**Comment by Layla-P** [comment]
Hey Brian,

Sorry I didnt get back to you.  As you know I can't do this at work as we
dont have fit and personally it's been a tough couple of weeks.

I'd still like to contribute but not sure what.

Kind regards,

Layla

**Comment by dgutride** [comment]
Replaced by #1043 - closing this PR - thanks for kicking off this conversation.

**Pull request closed without merging**
