### PR TITLE
Updates bootstrap-datepicker

### PR DESCRIPTION
**Pull request by priley86**
- noted jquery v3 [fix](https://github.com/eternicode/bootstrap-datepicker/commit/df4542c95ba126a3847e5d275d71897b8f79b086) in latest release of bootstrap-datepicker

### CODE REVIEW

**Comment by dlabrecq** [comment]
LGTM

**Comment by dgutride** [comment]
Looks good

**Comment by jeff-phillips-18** [comment]
LGTM

**Comment by priley86** [comment]
@dlabrecq @jeff-phillips-18 @dgutride thanks!

**Pull request merged**
