### PR TITLE
Bumped version number to 3.5.1

### PR DESCRIPTION
**Pull request by dlabrecq**
@dtaylor113 @jeff-phillips-18 please review

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
LGTM

**Comment by dtaylor113** [comment]
Hi, previous version bump included a lot of 'test' files.:
https://github.com/patternfly/patternfly/commit/3df2ad06fe89302d01b20c03cd91ecb7ccbccbce

Just verifying that there are none in this version bump.

**Comment by dlabrecq** [comment]
I always start with a new workspace, shrinkwrap, etc., but that's all the build generated this time.

**Comment by jeff-phillips-18** [comment]
In general, those files should not be changed by bumping the release.

**Comment by dtaylor113** [comment]
Hi, any reply to my question about including test files?  -thanks

**Comment by dtaylor113** [comment]
Ok, then LGTM :-)

**Comment by dlabrecq** [comment]
Like I said, nothing else changed for me, including test files.

**Comment by dlabrecq** [comment]
Can someone please merge?

**Pull request merged**
