### PR TITLE
Adds 11 new status icons

### PR DESCRIPTION
**Pull request by andresgalante**
## Description

Closes [PTNFLY-2447](https://patternfly.atlassian.net/browse/PTNFLY-2447)

This PR adds 11 new status icons:
https://rawgit.com/andresgalante/patternfly/PTNFLY-2447-new-status-icons-dist/dist/tests/icons.html

@jennyhaines @mcarrano  can you please review this one?

Also, @bleathem @jeff-phillips-18 or anyone elase can you merge after jenny or matt is ok with it?

Thanks!!

### CODE REVIEW

**Comment by jennyhaines** [comment]
@andresgalante - that was quick! So, a couple changes. The following icons that should currently be in the font, but are not showing up for me in the rawgit link are:









Also, the "pficon-off" icon should be red, and the "pficon-on" and "pficon-on-running" should be green on the Patternfly Icons page.

**Comment by jennyhaines** [comment]
Another update: I think we should take out these recommended Font Awesome icons (since we have custom versions in our own PatternFly icon font):

**Comment by jennyhaines** [comment]
Another thing to change- I think we should take out these recommended Font Awesome icons since we have custom versions in the PatternFly icon font:

**Comment by andresgalante** [comment]
😞 it seems that someone has updated icons without updating the json file. I'll make sure to re add the missing ones.

**Comment by andresgalante** [comment]
Hi @jennyhaines, Can you please check again? I've added the icons and changed the default color of "pficon-off", "pficon-on" and "pficon-on-running"

Thanks a lot for your help 😄

**Comment by jennyhaines** [comment]
Thanks for making the changes @andresgalante ! A couple more things, and then we're good:

These icons should not be listed in the "Recommended Font Awesome Icons" list, because we have our own versions of these icons in our PatternFly Icon Font:
unlock alt
lock
poweroff

This icon should be listed in the "Recommended Font Awesome Icons" list, but is not in rawgit:
arrowcircleup

There are two instances of this same icon in our PatternFly font, and I think we should just keep the one called "spinner":
spinner
running

**Comment by andresgalante** [comment]
Hi Jenny,

Please take a look here:
https://rawgit.com/andresgalante/patternfly/PTNFLY-2447-new-status-icons-dist/dist/tests/icons.html

Those icons are on patternfly, the website is not reflecting it. @LHinson  if @jennyhaines is ok, can we add a story to fix the website and merge this one?

**Comment by jennyhaines** [comment]
@andresgalante - I'm unclear on what you mean. So are you saying that you took out "pficon-running", "fa-power-off", "fa-lock", and "fa-unlock-alt", but they are still showing up on the website/rawgit? The rest of the icons look good to me.

**Comment by jennyhaines** [comment]
Also, @andresgalante , I have been talking with Serena, and she thinks we can scrap the "pficon-rebooting" icon. Would you mind deleting that icon from PatternFly? (We are just going to recommend using the restart icon for that use case instead.) Sorry for the runaround.

**Comment by andresgalante** [comment]
@jennyhaines I've removed  “pficon-running”, “fa-power-off”, “fa-lock”, "pficon-rebooting" and “fa-unlock-alt”.

Thanks a lot!

**Comment by jennyhaines** [comment]
Looks good to me! Thank you @andresgalante - ready to merge!

**Comment by andresgalante** [comment]
@bleathem @jeff-phillips-18 @cdcabrera @srambach or anyone else :) can you guys merge it please?

**Comment by jennyhaines** [comment]
Looks perfect- ready to merge!

**Comment by cdcabrera** [comment]
@andresgalante can do

**Review by cdcabrera — APPROVED** [review]

**Pull request merged**
