### PR TITLE
Return a handle to allow js to toggle the collapsed state of the vertical navigation bar

### PR DESCRIPTION
**Pull request by gashcrumb**
## Description
A few sentences describing the overall goals of the pull request's commits.
Include related PRs or Issues

Fixes https://github.com/patternfly/patternfly/issues/580

Now calling `$.setupVerticalNavigation()` returns an object with 3 functions:

```
var myNav = $.setupVerticalNavigation();

// collapse the vertical nav
myNav.collapseMenu();

// expand the vertical nav
myNav.expandMenu();

// Check if the nav is already collapsed:
console.log("Nav collapsed? : ", myNav.isCollapsed());
```

## Todos
- [ ] cross browser test
- [ ] Are you sure it works on IE9?
- [ ] Is it reponsive?

## Steps to test or reproduce and link to rawgit
Outline the steps to test or reproduce the PR here.

```sh
git pull --prune
git checkout <feature_branch>
bundle; script/server
```

I tested against `dist/tests/vertical-navigation-primary-only.html` and `dist/tests/vertical-navigation-with-secondary.html` though the former is how we're currently using the nav bar.

Also, you may want to please any @mentions you'd like to review.
@LHinson @andresgalante FYI, lemme know what changes are required or if there's any questions.  Thanks!

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
This looks good. The only issue I see is that if a user were to shrink the browser width down to mobile mode and then back out of mobile mode, the collapsed state would be lost. Granted this is already an issue when the user does explicitly collapse the menu and does the same thing.

**Comment by gashcrumb** [comment]
@jeff-phillips-18 is that relevant to this PR though?  i.e. does it happen on master without this enhancement in place?  If so I'd suggest raising it as a separate issue so a separate PR can be developed.

**Comment by jeff-phillips-18** [comment]
Well, if the particular view does not ever want to show the navigation menu, then simply shrinking and the expanding again would show the menu. In the other case, the user only loses what they did to hide the menu and they can re-hide it.

**Comment by gashcrumb** [comment]
Yep, good point, I'll take a look at that and likely have a commit to add to this PR then.

**Comment by gashcrumb** [comment]
Cool, so this worked out really well.  I refactored the mobile state change code into separate functions and used those instead, also turns off resize handling when the API is used to hide the menu, so that observed behavior doesn't happen.  Also made the function act like a singleton, as I found that calling the setup function a second time messes up the click handling for the toggle icon at the top-left of the page.

Changed the function names too:

```
var myNav = $.setupVerticalNavigation();

// collapse the vertical nav
myNav.hideMenu();

// expand the vertical nav
myNav.showMenu();

// Check if the nav is already collapsed:
console.log("Nav collapsed? : ", myNav.isVisible());
```

**Comment by gashcrumb** [comment]
Any time to review this PR?  Would love to have this functionality.

**Review by jeff-phillips-18 — APPROVED** [review]
👍 

Looks great. Thanks!

**Comment by bleathem** [comment]
The code changes look good.  I verified the changes locally on http://localhost:9000/vertical-navigation-with-secondary.html using:
```
$('.nav-pf-vertical').setupVerticalNavigation().showMenu()
$('.nav-pf-vertical').setupVerticalNavigation().hideMenu()
```

:+1:

Thanks for the contribution @gashcrumb !

**Comment by bleathem** [comment]
I rebased and pushed your branch manually, github didn't pick it up and close the PR, so I'm closing it manually.

**Comment by gashcrumb** [comment]
@bleathem awesome, thanks!

**Pull request closed without merging**
