### PR TITLE
Adding bar chart drill down and moving legend on horizontal bar chart

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by rhamilto** [comment]
Don't merge this one yet, @andresgalante, @dtaylor113, or @jeff-phillips-18.  Waiting for sign off from stakeholders.

**Comment by rhamilto** [comment]
@andresgalante, @dtaylor113, or @jeff-phillips-18, review and merge, please.

**Comment by dtaylor113** [comment]
LGTM

**Comment by jeff-phillips-18** [comment]
LGTM

**Pull request merged**
