### PR TITLE
#296 Adds color to table row when hover

### PR DESCRIPTION
**Pull request by andresgalante**
#296

Hi @rhamilto @sjcox-rh @cardosogabriel 
I changed the border to blue-100, 200 felt to strong. What do you think?

Sj, you can preview it here:
https://rawgit.com/andresgalante/patternfly/296-bug-fix/tests/tables.html

### CODE REVIEW

**Comment by rhamilto** [comment]
I think it needs more value (darker) so that the value of the hover border is consistent with the non-hover state.

**Comment by sjcox-rh** [comment]
Yeah I agree with Robb.  It matches the value of the non-hover state as well as the value of the top border on the hover state.

**Comment by andresgalante** [comment]
@rhamilto @sjcox-rh thanks! I just update it to blue-200, is it better?
SJ check it here:
https://rawgit.com/andresgalante/patternfly/296-bug-fix/tests/tables.html

**Comment by sjcox-rh** [comment]
@andres YAS!  Thanks :]

On Thu, May 26, 2016 at 3:08 PM, Andres Galante notifications@github.com
wrote:

> @rhamilto https://github.com/rhamilto @sjcox-rh
> https://github.com/sjcox-rh thanks! I just update it to blue-200, is it
> better?
> SJ check it here:
> https://rawgit.com/andresgalante/patternfly/296-bug-fix/tests/tables.html
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/patternfly/patternfly/pull/297#issuecomment-221965166

## 

_Sarah Jane Cox_
User Interaction Designer
User Experience Design Team

Red Hat, Inc.
http://www.redhat.com/about/whoisredhat/redhatstories.html?intcmp=70160000000TB9vAAG&

**Comment by andresgalante** [comment]
@sjcox-rh @rhamilto thanks a lot 😄

**Pull request merged**
