### PR TITLE
[*WIP*] Implementing showcase design changes for CSS 

### PR DESCRIPTION
**Pull request by asonawan**
## Description
Implementing new design mockups/templates for CSS Showcase.

## Current Tasks

- [x] Add set of initial components
- [x] Add get-started page 
- [x] Add contribution page

## Future To-Do

- [ ] Update missing components
- [ ] Update the content on get started and contribute page

## Changes

- Set up initial CSS components for showcase 
- Added get-started installation guide page
- Added contribution page

## Link to rawgit and/or image

aug-28-2017 21-38-33

aug-28-2017 22-27-58

## PR checklist (if relevant)

- [ ] **Responsive**: works in extra small, small, medium and large view ports.

### CODE REVIEW

**Comment by junezhang** [comment]
@asonawan Thanks for your PR.

Here one needs to update. The showcase list we used PatternFly-Launcher.
Please reference this link to update. http://rawgit.com/junezhang/showcase/master/index.html
screen shot 2017-09-06 at 12 07 08 pm

**Comment by asonawan** [comment]
@junezhang I have updated the application launcher at every places.

What should we be using the font size for the body, should it be 12px or 14px?

**Comment by junezhang** [comment]
@asonawan, currently, PatternFly-showcase is consistence with patternfly-core to use 12px for body.

**Comment by asonawan** [comment]
@junezhang we were using 14px for the showcase which I have removed to keep it consistent.
Updated links for get started and contribute page.

**Comment by bleathem** [comment]
I've merged this PR into the jquery-showcase branch.  I will rename that branch to simply `showcases`.

Thanks for the contributoion @asonawan!  Let's coordinate further on the showcases branch.

**Pull request closed without merging**
