### PR TITLE
Update application launcher test pages

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
## Description

Adds a single test page for all varieties of the application launcher and updates the application launcher horizontal navigation page to show full page. Uses a common include for the application launcher's html. There are no css or distribution changes in this PR.

## Changes

* Adds a single page to see all versions of the application launcher under widgets.
* Uses full page for the horizontal navigation for application launcher page.
* Add a common include for the the application launcher html.

## Link to rawgit

http://rawgit.com/jeff-phillips-18/patternfly/launcher-dist-2/dist/tests/index.html

### CODE REVIEW

**Comment by matthewcarleton** [comment]
@jeff-phillips-18 It looks like the grid view isn't working. In the css I created a conditional that looks for `.applauncher-pf-block-list` on the `<ul>`

**Review by dtaylor113 — APPROVED** [review]
Other than the Grid view issue, LGTM

**Comment by jeff-phillips-18** [comment]
Thanks @matthewcarleton  I didn't propagate one of the variables. Fixed.

**Review by matthewcarleton — APPROVED** [review]
Great, thanks for taking care of this Jeff 👍

**Pull request merged**
