### PR TITLE
feat(icon): Add support for fontawesome v5

### PR DESCRIPTION
**Pull request by skateman**
## Description
Allow the usage of fontawesome 5 icons in PF3.

## Changes
Added the new FA prefixes into the codebase.
https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

### CODE REVIEW

**Review by jeff-phillips-18 — DISMISSED** [review]

**Comment by skateman** [comment]
@jeff-phillips-18 can this be merged?

**Comment by jeff-phillips-18** [comment]
Needs another reviewer. Added @mcoker

**Comment by mcoker** [comment]
@skateman is the purpose of this to support using a `.fa*` icon in the place of `.pficon` and `.fa` currently, or just in the place of `.fa`?

FWIW, I found these instances:

#### .fa is defined, but not updated to support `.fa*`
  * card-view.less L98
  * list-pf.less L59
  * sidebar.less L55, L71

#### .pficon is defined, but doesn't support `.fa*`
  * alerts.less L20
  * card-view.less L99
  * notification-drawer.less L155
  * toast.less L11-L16
  * type.less L14

**Comment by skateman** [comment]
@mcoker the first 3 are valid missing places, the rest are just pf-specific icon stylings on places where you cannot change the icon.

**Comment by skateman** [comment]
@jeff-phillips-18 @mcoker can you please re-review?

**Review by jeff-phillips-18 — APPROVED** [review]

**Review by mcoker — APPROVED** [review]
👍

**Pull request merged**
