### PR TITLE
fix(app launcher): rename inclusion variables

### LINKED ISSUE #738: Hyphenated variables and multiple inclusion do not work (application launcher)
The issue seems to be caused by liquid, pages built with jekyll are ok.

Application launcher uses hyphenated variables in include:

    {% include widgets/navigation/horizontal-primary-nav-bar.html launcher-icons=true launcher-grid=true navindex=1 %}

which are re-included in `horizontal-primary-nav-bar.html`:

    {% include widgets/framework/application-launcher.html launcher-icons=include.launcher-icons launcher-grid=include.launcher-grid %}

As far as I can tell on the first page the variable `include.launcher-grid` doesn't exist, instead of it there is `include.grid` so the second inclusion is broken. However even fixing the variable names doesn't work, it looks like re-including a variable turns it into a Promise and the variable is inaccessible at the time of the build.

### PR DESCRIPTION
**Pull request by michpetrov**
Rename variables used in application launcher pages. 
Variable names must not contain a hyphen, must be unique across the whole include chain and an include variable must not be referenced in another include tag (in the latter two cases `grunt build` will short-circuit without any explanation).

Closes #738

### CODE REVIEW

**Comment by andresgalante** [comment]
Hi @michpetrov thanks a lot for sending this PR.

I can't build your branch, it stops here:
```
Running "pages" task
Builidng test pages with liquid.js
Starting build...
Reading test pages...
```

If there a liquid thing that makes the build stop?

**Comment by michpetrov** [comment]
@andresgalante that's the bug I was running into. I have adjusted the variable names yet again (and added some pages I missed) now it should work.

**Comment by andresgalante** [comment]
Thanks a lot @michpetrov it works now 😄 

@jeff-phillips-18 @dlabrecq can you please help me to spot if this PR is affecting the website?

**Review by dlabrecq — APPROVED** [review]
LGTM

The patternfly-ng repo hasn't ported the app launcher yet, so this would only a potential issue for angular patternfly, right now.

**Comment by jeff-phillips-18** [comment]
This has no effect on consumers only on test pages.

**Review by jeff-phillips-18 — APPROVED** [review]
Test out the test pages and LGTM.

**Pull request merged**
