### PR TITLE
Adds bundle icon

### PR DESCRIPTION
**Pull request by andresgalante**
## Description

@kybaker asked me if I could help adding the new bundle icon, so this PR is adding the new bundle icon 😄 

@priley86 @jeff-phillips-18 @dlabrecq @bleathem can any of you guys test it and merge it please?

It should look like this:

bundle

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
LGTM

**Comment by priley86** [comment]
Looks good to me @andresgalante 👍

**Comment by dtaylor113** [comment]
Better late than never! :-) cloned this branch and verified that the bundle icon displays correct.

**Comment by andresgalante** [comment]
Thanks 😄

**Pull request merged**
