### PR TITLE
Overly specific bower dependencies #233

### PR DESCRIPTION
**Pull request by dlabrecq**
Modified moment dependency to be ~2.11

### CODE REVIEW

**Comment by dtaylor113** [comment]
This PR title is "Overly specific bower dependencies" which seem to imply multiple dependencies updated, whereas it was just for 'moment'.   Should we change all dependencies to have a "~" prefix on major release number?
Ex: 
~1.2.0: must be at least as high as 1.2.0 but less than the next major version

**Comment by dlabrecq** [comment]
I can make that change. Although, some dependencies use the caret character (e.g., "grunt-contrib-copy": "^0.8.1"). Probably shouldn't change those.

**Comment by dtaylor113** [comment]
Yes, I believe carrot has similar behavior

**Comment by dlabrecq** [comment]
Can this be merged?

**Comment by jeff-phillips-18** [comment]
LGTM

**Pull request merged**
