### PR TITLE
vertical nav: fix second level nav to close on item click

### LINKED ISSUE #672: In vertical navigation, the second level navigation is hanging open after clicking the menu option
In vertical navigation, the second level navigation is hanging open after clicking the menu option. Menus should close when options in them are clicked.

### PR DESCRIPTION
**Pull request by gregsheremeta**
Previously the second level navigation was hanging open after
clicking the menu option. Menus should close when options in
them are clicked, fixed.

## Description
Fixes #672 

ping @bleathem @priley86 @vojtechszocs

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
I am seeing this after clicking on a tertiary item:

image

**Comment by gregsheremeta** [comment]
What demo/test page is that? Can I use it?

**Comment by jeff-phillips-18** [comment]
Yeah, happens on the tertiary nav pages such as: 

https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/vertical-navigation-with-badges.html

**Comment by priley86** [comment]
this bug has been living for far too long...thanks a lot @gregsheremeta for finding the fix!

**Comment by gregsheremeta** [comment]
welcome. I hope to finalize this patch this week. It still has the bug Jeff noticed

**Comment by gregsheremeta** [comment]
@jeff-phillips-18  please retest

**Review by jeff-phillips-18 — APPROVED** [review]
👍   Thanks @gregsheremeta !

**Comment by gregsheremeta** [comment]
thanks, ETA on this making it into a release, and what version that would be?

**Pull request merged**
