### PR TITLE
Small text change to be more concise

### PR DESCRIPTION
**Pull request by LHinson**

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
LGTM

**Comment by dlabrecq** [comment]
LGTM.

FYI, I believe the preferred approach is to make changes in your own fork of the repo. Typically, you'll only see release branches here.

**Comment by bleathem** [comment]
@dlabrecq I'd argue that's not necessarily the _preferred_ approach.  I was advocating the opposite just yesterday in fact.  We should all feel comfortable opening feature branches in the main repo, particularly if we need to collaborate on developing a feature.  Perhaps a discussion we should take up on the Patternfly ML.

In this case the branch was crated using github's web tooling for editing files and submitting those results as a PR.  As we want to encourage more non-technical folks to contribute to patternfly repos, and working from a fork demonstrably complicates the process.

**Comment by bleathem** [comment]
Thanks for the PR @LHinson :+1:

**Comment by dlabrecq** [comment]
Yes, we should have a discussion. At a min., folks should clean up (delete) old branches.

**Pull request merged**
