### PR TITLE
chore(single-sign-on): make img paths more dynamic

### LINKED ISSUE #968: Change image paths on single sign on to be dynamic for org to consume
I am in the process of adding the single-sign-on code example to pf-org using the `login-single-sign-on.html` as an include. Currently the google drive svg, gmail svg, and google calendar svg have paths of:

`{{site.assets-base}}/img/google-drive.svg"`
`{{site.assets-base}}/img/gmail.svg`
`{{site.assets-base}}/img/google-calendar.svg`

pf-org cannot find this path because it points to `/patternfly-org/img/{name}.svg` instead of `/patternfly-org/assets/img/{name}.svg` 

Images inside of org are in an assets directory. To solve this issue and make it more dynamic for org to consume, they each would need to be changed to something like this for example: `{{site.assets-base}}/{{site.google-drive}}"` then create a google-drive variable in the `_config.yml` file and have it point to `google-drive: /img/google-drive.svg` which would then allow me in pf-org to add the svg's to the `assets/img` directory and in the `_config.yml` file have it point to `google-drive: assets/img/google-drive.svg` so that it associates that variable to the correct path that pf-org can recognize

I had to do this with `brand-horizontal` when using the html from `login-basic.html` in this [PR](https://github.com/patternfly/patternfly-org/pull/526/files#diff-e6422af2c5a3ea680839278540cfdf29R14)

I can take on this issue if you want @matthewcarleton @cliffpyles.

### PR DESCRIPTION
**Pull request by amarie401**
## Description
Related and fixes #968 

## Changes

* `_config.yml` is updated with img paths and variables
* `login-single-sign-on.html` is updated with variables

### CODE REVIEW

**Comment by matthewcarleton** [comment]
hey @amarie401 can you post the rawgit link for this?

**Comment by amarie401** [comment]
@matthewcarleton https://rawgit.com/amarie401/patternfly/single-sign-on-img-path-dist/dist/tests/login-single-sign-on.html

**Review by matthewcarleton — APPROVED** [review]
great work!

**Comment by amarie401** [comment]
Thanks!

**Comment by amarie401** [comment]
@andresgalante could you review as well?

**Comment by andresgalante** [comment]
The code looks ok, thanks a lot @amarie401

@LHinson if we are ok showing copyrighted logos, please merge it

**Comment by LHinson** [comment]
Late to the game but yep, we are covered as we have info covered in the docs

**Pull request merged**
