### PR TITLE
Bumped version number to 3.3.2

### PR DESCRIPTION
**Pull request by dlabrecq**

### CODE REVIEW

**Comment by dtaylor113** [comment]
LGTM

**Comment by jeff-phillips-18** [comment]
Should this be 3.4.0 or 3.3.2? Is this a bug fix release?

**Comment by jeff-phillips-18** [comment]
I believe we also need to update the version number in bower.json

**Comment by dlabrecq** [comment]
I only see a couple bug fixes in the commits, so I chose v3.3.2. The version number in both bower.json and package.json have been updated?

**Comment by jeff-phillips-18** [comment]
OK, I missed the bower.json change my bad.

Just wanted to make sure the version number change was intentional, I agree with your assessment.

LGTM

**Pull request merged**
