### PR TITLE
Add ability to click icon on the mini aggregation status card (1466)

### PR DESCRIPTION
**Pull request by dgutride**
Icons should be clickable on the mini aggregation status cards now.  The dist changes are broader than what I changed but are the output from the build.

### CODE REVIEW

**Comment by dtaylor113** [comment]
LGTM

**Comment by jeff-phillips-18** [comment]
Please make the same change to the following locations of mini aggregate status cards:

tests-src/_includes/widgets/layouts/cards-alt.html L37
tests-src/_includes/widgets/layouts/cards.html L61
tests-src/_includes/widgets/layouts/cards.html L76
tests-src/_includes/widgets/layouts/cards.html L91

**Comment by jeff-phillips-18** [comment]
LGTM, please squash your commits.

**Comment by dlabrecq** [comment]
While running the test pages, I noticed that not all icons are clickable. In the full page cards example, I see the mini cards; amet and adipiscing are clickable, but ispum, lorem, dolar sit and consectetur are not. I kind of expected to see all icons clickable if there is a link available in the card?

**Comment by dlabrecq** [comment]
After the last push, the icons are clickable.

**Pull request merged**
