### PR TITLE
Node LTS4 - Travis upgrade and README note

### PR DESCRIPTION
**Pull request by priley86**
## Travis Node 4 Upgrade

The goal of this PR is to satisfy requirements of [PTNFLY-1767](https://patternfly.atlassian.net/browse/PTNFLY-1767) and [PTNFLY-1766](https://patternfly.atlassian.net/browse/PTNFLY-1766), and ensure Core P.F. builds properly with Node 4 LTS.
## Changes

Surprisingly, there is very little code changes. I have attempted to run our build/unit tests in my fork with Travis [here](https://travis-ci.org/priley86/patternfly/builds/164984186) with Node 4. It appears all unit tests and build steps pass.
## PR checklist (if relevant)
- [x] **Cross browser**: works in IE9
- [x] **Cross browser**: works in IE10
- [x] **Cross browser**: works in IE11
- [x] **Cross browser**: works in Edge
- [x] **Cross browser**: works in Chrome
- [x] **Cross browser**: works in Firefox
- [x] **Cross browser**: works in Safari
- [x] **Cross browser**: works in Opera
- [x] **Responsive**: works in extra small, small, medium and large view ports.
- [ ] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

### CODE REVIEW

**Comment by priley86** [comment]
@bleathem @dlabrecq @dgutride would appreciate a second set of eyes. What am I overlooking?

**Comment by bleathem** [comment]
Wow, minimal code changes indeed.  Let's consider making the same change to the a-pf, pf-org, and rcue repos as well.

**Comment by dlabrecq** [comment]
LGTM

**Comment by andresgalante** [comment]
@priley86 thanks a lot, I'll merge this one

**Pull request merged**
