### PR TITLE
Making branded SVG images available via PatternFly 

### PR DESCRIPTION
**Pull request by dtaylor113**
The following brand images/svgs were added to '/dist/img' directory
- Kubernetes (pending legal permission)
- OpenShift
- Atomic

Also including latest tests/\* files

### CODE REVIEW

**Comment by LHinson** [comment]
Awesome! Thanks Dave :)

**Comment by jeff-phillips-18** [comment]
what does "Kubernetes (pending legal permission)" mean? Holding this PR off until approved?

**Comment by dtaylor113** [comment]
From @LHinson : "yes, got approval [for Kubernetes] from Erin Campion in legal on Feb 23 via e-mail. "

**Comment by jeff-phillips-18** [comment]
LGTM

**Pull request merged**
