### PR TITLE
Adds 10 new icons

### PR DESCRIPTION
**Pull request by andresgalante**
This PR is adding 10 new icons.

Take a look @jennyhaines 😄 

https://rawgit.com/andresgalante/patternfly/PTNFLY-2505-add-new-icons-dist/dist/tests/icons.html

### CODE REVIEW

**Comment by serenamarie125** [comment]
@andresgalante thanks for getting these in before heading out on vacation!

**Comment by jennyhaines** [comment]
@andresgalante - It looks great! I see all of those 10 new icons. Thanks so much :)

**Comment by bleathem** [comment]
The pf-org icons page (hosted in the pf-design repo) needs to be updated with these new icons.
https://github.com/patternfly/patternfly-design/blob/master/styles/icons/icons.md

**Comment by LHinson** [comment]
I'll add a new story for the table update @bleathem Going to merge this PR.

**Pull request merged**
