### PR TITLE
fix(package.json) run grunt after successful build for npm start

### PR DESCRIPTION
**Pull request by vkrizan**
## Description
`npm start` started grunt server before the build was finished in
separate process.  Terminating main process with CTRL-C did not
terminated grunt server.

This fix adds a condition to `npm start` to start grunt server after the
build is successful.

## Changes

* fixed `npm start` command with condition

### CODE REVIEW

**Comment by andresgalante** [comment]
@vkrizan thanks a lot 👍 

@priley86 Can you please review and merge this one?

**Comment by vkrizan** [comment]
I am not sure if `& open ...` should work, because it does not for me. I don't even have `open` command/bin.

**Comment by bleathem** [comment]
I added a commit moving the `open` command to the Gruntfile.js config, and simplified the npm start command.

**Review by bleathem — APPROVED** [review]

**Comment by vkrizan** [comment]
@bleathem ack. Thanks.

**Review by cdcabrera — APPROVED** [review]
Looks good!

Maybe at some point, since this implements NPM Open, we could eventually pass browser parameters through

**Pull request merged**
