### PR TITLE
fix(context selector): styles match dropdowns

### PR DESCRIPTION
**Pull request by matthewcarleton**
This updates the style of the context selector to match the dropdown menu as per requested in #981. 
https://rawgit.com/matthewcarleton/patternfly/context-selector-981-dist/dist/tests/context-selector.html

### CODE REVIEW

**Comment by rhamilto** [comment]
@matthewcarleton, can you provide a screenshot or rawgit link?  Thanks.

**Comment by matthewcarleton** [comment]
@rhamilto updated now. I was impatient with travis :)

**Review by rhamilto — APPROVED** [review]
Thanks, @matthewcarleton.  I think these changes improve the "fit" of the context selector within PatternFly.

**Review by amarie401 — APPROVED** [review]
LGTM! Thanks @matthewcarleton 👍

**Pull request merged**
