### PR TITLE
Correct pficon class in navbar

### PR DESCRIPTION
**Pull request by knokit**

### CODE REVIEW

**Comment by andresgalante** [comment]
Good catch with the icons names @knokit thanks 😄 

@knokit Why are you removing the test.css file?

@jeff-phillips-18 @srambach can you please review this one?

**Comment by knokit** [comment]
> Why are you removing the test.css file?

Not sure how that happened. I just ran build and it removed test.css.

**Comment by jeff-phillips-18** [comment]
Please use jekyll 2.5.3 to build, that should fix the test.css issue.

**Comment by knokit** [comment]
@jeff-phillips-18 Fixed! Thanks

**Comment by jeff-phillips-18** [comment]
LGTM

**Comment by andresgalante** [comment]
@knokit thanks a lot!!

**Pull request merged**
