### PR TITLE
fix(wizard): robust mobile wizard

### PR DESCRIPTION
**Pull request by matthewcarleton**
## Description
This is a more robust version of the current wizard for mobile support. The old version is still supported so I've created an alternative rather than replace the current one. The existing wizard is now marked as wizard(old).  

This version still needs js consideration and I would like to talk about the multiple implementations of the wizard code. 

## Link to rawgit and/or image

https://rawgit.com/matthewcarleton/patternfly/advanced-wizard-dist/dist/tests/wizard.html

## PR checklist (if relevant)

- [x] **Cross browser**: works in IE9
- [x] **Cross browser**: works in IE10
- [x] **Cross browser**: works in IE11
- [x] **Cross browser**: works in Edge
- [x] **Cross browser**: works in Chrome
- [x] **Cross browser**: works in Firefox
- [x] **Cross browser**: works in Safari
- [x] **Cross browser**: works in Opera
- [x] **Responsive**: works in extra small, small, medium and large view ports.
- [x] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

### CODE REVIEW

**Comment by andresgalante** [comment]
@LHinson are you ok with renaming the old wizard to Wizard(old) and introducing the new one as the recommended version?

**Comment by andresgalante** [comment]
@matthewcarleton there is a problem with the line on the left, it moves and shifts depending on the viewport size

img

That must be due to the subpixel position of the modal, this would not happen if the wizard was outside a modal.

**Comment by matthewcarleton** [comment]
@andresgalante is it actually showing up on different mobile sizes or is that just when you resize your browser window?

**Comment by andresgalante** [comment]
@matthewcarleton when hove over the subitems, they shift a bit to the right to accommodate for the space of the border. Can you add a transparent border to them and them add a color on hover/active please?

**Comment by matthewcarleton** [comment]
@andresgalante good catch. Done :)

**Review by andresgalante — DISMISSED** [review]
@LHinson @jeff-phillips-18 @dlabrecq @dgutride @priley86:

I am ok to merge this one, but I'd like for all of us to be aware of what this PR is doing:

Due to how the design was done, this is not a responsive component. It's adding a mobile version for the steps. Meaning that we'll force to have duplicated information in the DOM and showing or hiding parts according to the viewport.

We have the same case on the vertical nav.

Both designs should be corrected for the next version of patternfly were no component will be merge unless it's responsive.

**Comment by priley86** [comment]
No issues on this PR. Please nudge me though once this is merged please. ⏰

**Comment by jeff-phillips-18** [comment]
@andresgalante Would it be better to take the time to make this a 'responsive component' now? Would doing so break the existing wizard usage?

**Comment by matthewcarleton** [comment]
@jeff-phillips-18 @andres is on vacation, but this might be a question for @LHinson. I believe we would have to revisit design to understand how this translate to desktop, which would add more time. I think the idea is we are going to correct these things in PF-next.

**Review by jeff-phillips-18 — DISMISSED** [review]

**Review by LHinson — DISMISSED** [review]

**Pull request closed without merging**
