### PR TITLE
Add Function c3ChartDefaults to provide defaults for C3 Charts

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Current support:
  default colors
  default donut chart settings
  default spark line charts settings

### CODE REVIEW

**Comment by dtaylor113** [comment]
LGTM

**Comment by rhamilto** [comment]
looks good.  

one question, @jeff-phillips-18. should any of charts on http://rawgit.com/patternfly/patternfly/master/tests/cards.html be updated to use these new defaults?

**Comment by jeff-phillips-18** [comment]
@rhamilto Yes the should. Thanks, working on it.

**Comment by jeff-phillips-18** [comment]
Updated the cards to use the c3ChartDefaults function.

**Comment by jeff-phillips-18** [comment]
Updated the cards and dashboard pages to use the new function

**Comment by rhamilto** [comment]
Looks good.  @dtaylor113 confirm and merge?

**Comment by dtaylor113** [comment]
LGTM

**Pull request merged**
