### PR TITLE
Update the icon files and CSS icon definitions

### PR DESCRIPTION
**Pull request by bleathem**
These font changes contributed by @jennyhaines have been staged for review here:
https://bleathem.github.io/patternfly-org/styles/icons/

### CODE REVIEW

**Comment by jennyhaines** [comment]
@bleathem - this looks "spot-on"...jolly good! Thank you!

**Comment by jennyhaines** [comment]
+1

**Comment by andresgalante** [comment]
looks good 👍

**Comment by LHinson** [comment]
+1

**Pull request merged**
