### PR TITLE
PTNFLY-1208 changes color of validation error on forms

### PR DESCRIPTION
**Pull request by andresgalante**
@dlabrecq @dtaylor113 @jeff-phillips-18 This is a simple change of colors on error validation messages on forms.

I don't know why I get `<link href="tests.css" rel="stylesheet" media="screen, print">` added to every single test page. Can you help me out figuring what I am doing wrong?

thanks!

### CODE REVIEW

**Comment by andresgalante** [comment]
I was running a wrong version of jekyll. thanks @jeff-phillips-18 !

**Comment by jeff-phillips-18** [comment]
LGTM

**Comment by dlabrecq** [comment]
LGTM

**Comment by andresgalante** [comment]
Please don't merge this PR yet. 
I've added form examples widgets for the demo page. I want to check with @dlabrecq if I did things correctly, specially regarding CSS specific just for the docs to make the modal visible.

**Comment by dlabrecq** [comment]
Whatever is in the template will be visible to developers on the new site, via pretty-print code snippets.

Thinking it would be best to pull the CSS out of the template, unless developers need it for their own code? If it's necessary, perhaps it should be included in modals.less?

Noticed pf-example-modal appears to override modal, so maybe we can also omit the modal class here? If so, the div with the pf-example-modal class could be moved outside the template.

**Comment by andresgalante** [comment]
@dlabrecq Thanks, it makes much better sense to me know. Can we include the doc specific styles into the docs css?

**Comment by dlabrecq** [comment]
Not certain which file you're referring to?

**Comment by dlabrecq** [comment]
LGTM

**Comment by andresgalante** [comment]
Thanks! Please don't merge this one yet. I'll change the demo class name and wait for @serenamarie125 to review the visuals.

**Comment by andresgalante** [comment]
@dlabrecq @jeff-phillips-18 @dtaylor113 This PR changes color of error messages and removes margin-bottom on `help-block` to reduce vertical movement when error messages appear.

@dabeng Can you please take another look at the widget page to see if the includes are ok there to generate the code snippet on the new website.

Thanks!

**Comment by dtaylor113** [comment]
LGTM

**Comment by jeff-phillips-18** [comment]
👍

**Comment by dlabrecq** [comment]
Looks good! Just branch conflicts to be resolved.

**Comment by andresgalante** [comment]
Sorry there weren't conflicts when I send it this morning, I'll rebase. Thanks for the review !

**Comment by andresgalante** [comment]
@dlabrecq no more conflicts :)

**Pull request merged**
