### PR TITLE
Form labels

### PR DESCRIPTION
**Pull request by matthewcarleton**
## Description
This offers a new left aligned label for forms. 
The field level help was also introduced to this page. The required field "*" has been moved to the left side of the label to make room for the field level help.

I've also updated the icon colour to grey across Patternfly so it's reflected on the forms test page and the popover page as well.

To left align fields the `.form-horizontal-pf-left-align" is required.
If there are both required and optional fields the `.required-pf` is needed on the form and the corresponding label of any required input.

##Jira Story

https://patternfly.atlassian.net/browse/PTNFLY-2775

## Changes

Write a list of changes the PR introduces

* For all required labels it moves the "*" to the left instead of the right.
* The forms page now shows the inline help.
* The Forms page now shows examples of left aligned labels
* The Popup page reflects the colour change for the pficon-info

## Link to rawgit and/or image

https://rawgit.com/matthewcarleton/patternfly/form-labels-dist/dist/tests/forms.html
https://rawgit.com/matthewcarleton/patternfly/form-labels-dist/dist/tests/popovers.html
## PR checklist (if relevant)

- [ ] **Cross browser**: works in IE9
- [ ] **Cross browser**: works in IE10
- [x] **Cross browser**: works in IE11
- [x] **Cross browser**: works in Edge
- [x] **Cross browser**: works in Chrome
- [x] **Cross browser**: works in Firefox
- [x] **Cross browser**: works in Safari
- [x] **Cross browser**: works in Opera
- [x] **Responsive**: works in extra small, small, medium and large view ports.
- [x] **Preview the PR**: An image or a URL for designer to preview this PR is provided.

### CODE REVIEW

**Comment by mcarrano** [comment]
@matthewcarleton These changes look great! There is only one small request. That's to make the hover color on the "i" icon blue.

**Comment by nlcwong** [comment]
@matthewcarleton in the case where the labels are right-aligned, would it be possible to have the info icon hanging in the space between the label and field component so that the info icon would be sticking out on its own?  (Similar to the issue with the asterisks hanging out over on its own, but reverse.)

Would like to achieve symmetry in that the labels' edges are aligned with one another.

**Comment by matthewcarleton** [comment]
@mcarrano thanks, I'll make those changes to the icon.
@nlcwong I did explore that but ran into issues with how that styling would affect the popover due to the positioning. If we did want to explore that further we may need to expand the scope of this to refactor how the popup is positioned. @mcarrano what are your thoughts on this? I think that while that could look nice I'm not sure it's worth the effort of exploring it.

**Comment by matthewcarleton** [comment]
@mcarrano I've made those updates. I've used pf-black-900 for the grey and left the default for the blue. In the design @nlcwong used #333333 for black but that doesn't exist in our colour palette so I used the closest one.

**Comment by mcarrano** [comment]
@matthewcarleton Are your latest changes implemented in the test pages, because I'm not seeing them there. Regarding the positioning of the "i" icon, can you remind me what the popover positioning issue is?

**Comment by matthewcarleton** [comment]
@mcarrano I just pushed again which should update the test pages. I'm not sure why it didn't show earlier :(
When adjusting the positioning of the "I" icon we then have to adjust the popover because of the nature of how the popover is built. I can show you what I mean if that's helpful as well.

**Comment by jeff-phillips-18** [comment]
Should the popover on bottom with a title have the arrow be shaded the color of the title bar? Looks a bit odd with the white to me.

**Comment by matthewcarleton** [comment]
@jeff-phillips-18 yup I'd agree with that. I think that would be a new issue though, this is more about form label stuff.

**Comment by matthewcarleton** [comment]
@mcarrano @nlcwong are we good to merge this now?

**Comment by nlcwong** [comment]
@matthewcarleton I'm trying to get screenshots of the code changes to put in the design docs, but the  test page seems to not be updated with your latest changes because when i hover over the i icon, the text input field is in focus, but the i icon itself does not turn blue on hover.  Everything else seems fine.

**Comment by matthewcarleton** [comment]
@nlcwong I've just updated with those changes. Sorry for the delay I was on PTO :)

**Comment by nlcwong** [comment]
@matthewcarleton no worries, i just used what I could and explained the rest away in text. Also is there some sort of refresh thingy i need to do, still can't see it from the links you posted above.

**Comment by matthewcarleton** [comment]
@nlcwong really strange, worked locally but not once Travis built it out. I added some explicit css to make it work, should be good now :)

**Review by mcarrano — DISMISSED** [review]
Looks good @matthewcarleton Thanks for all your work on this!

**Review by andresgalante — APPROVED** [review]

**Pull request merged**
