### PR TITLE
Gitignore generated dist files

### PR DESCRIPTION
**Pull request by priley86**
- adds dist to gitignore
- adds after_success script step which publishes dist files to release branch on successful builds with commits in master
- test pages are frequently used by Patternfly team for testing, so it is preferable to update these after each commit (vs just on tagged commits)

### CODE REVIEW

**Comment by priley86** [comment]
@dlabrecq @dgutride please take a look at this one and let me know if you see any issue. Will need some help sometime this week setting up the Travis variables and adjusting if needed.

**Comment by priley86** [comment]
Linking [PTNFLY-1589](https://patternfly.atlassian.net/browse/PTNFLY-1589)

**Comment by bleathem** [comment]
Before we add `/dist` to the `.gitignore` file, we need to make sure it's fully re-creatable.  Seems like we need to pull [PTNFLY-1600](https://patternfly.atlassian.net/browse/PTNFLY-1600) into the current sprint as a blocker to [PTNFLY-1589](https://patternfly.atlassian.net/browse/PTNFLY-1589).

**Comment by priley86** [comment]
@bleathem I've pulled in [PTNFLY-1600](https://patternfly.atlassian.net/browse/PTNFLY-1600). I'm glad you caught this! Will look at adding a grunt step for copying `src/img`to `dist/img` today.

Also - I just realized I will also have to update our `tests/index.html` redirect to point at `release`. 

Let me know if you see anything else needed here :)

**Comment by priley86** [comment]
@bleathem @dlabrecq @dtaylor113 I've updated this PR to ensure `src/fonts` and `src/img` are copied to `dist`. Also noted that symlink files `dist/css/styles.css` and `dist/css/styles-additions.css` are dated and should probably be removed. Any thoughts on those @dtaylor113 ?

Can you review once more? Also - will need help ensuring the `.travis.yml` variables are correct.

**Comment by priley86** [comment]
@dgutride also - any thoughts here?

**Comment by dgutride** [comment]
This looks good to me - we'll need to set the configuration values on travis for this to work, too.

**Comment by dlabrecq** [comment]
LGTM. Have you been able to setup Travis to test your fork?

If not, it might be best to perform a trial run on your fork prior to merging. Need to ensure it runs when creating a PR, merge and tag.

**Comment by priley86** [comment]
@dgutride @dlabrecq thanks for the help this morning! I will test it in my fork shortly.

**Comment by bleathem** [comment]
I can confirm that after deleting the `/dist` folder and re-running the build, the `/dist` folder is re-created with only the `/dist/css/styles.css` and `/dist/css/styles-additions.css` files missing.

If the travis stuff is worked out, then I'd say we are ready to merge.

**Comment by priley86** [comment]
@dlabrecq @bleathem @dgutride this should be ready to go - I tested all three scenarios @dlabrecq mentioned in my fork. Let's merge tomorrow A.M.

**Comment by priley86** [comment]
@dlabrecq i've rebased and merged latest. Do you mind merging this when you have a moment?

**Comment by dlabrecq** [comment]
Looks like there are conflicts, again? Need to rebase one more time.

**Pull request merged**
