### PR TITLE
chore(tests): enable all regression tests

### PR DESCRIPTION
**Pull request by cliffpyles**
## Description
Enables visual regression tests for all pages.

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
The new images for chart components do not look correct.

**Comment by cliffpyles** [comment]
Good catch. I'll update them.

**Comment by dgutride** [comment]
@cliffpyles - agree with Jeff, not just the chart images, others have overlapping text like the accordion.  Any idea what would cause that?

**Comment by jeff-phillips-18** [comment]
Fixed height accordion is likely due to the window size not being computed and acted upon prior to the screen capture.

**Comment by cliffpyles** [comment]
Updates done.

**Comment by cliffpyles** [comment]
While I debug the CI issues, I'm going to close this PR to eliminate extra CI load and noise.

You can track the progress here: https://github.com/cliffpyles/patternfly/pull/5

**Pull request closed without merging**
