### PR TITLE
Fixed the issue #395

### PR DESCRIPTION
**Pull request by junezhang**
Need to remove this right-border in toolbar view selector
https://github.com/patternfly/patternfly/issues/395

When I check the new toolbar page, I found there is a bug, there is a right border in the element of view selector. So create this PR to fix it.

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
LGTM

**Comment by junezhang** [comment]
@srambach Could you help to review it? Thanks.

**Comment by srambach** [comment]
I hate to see this nested again because it is having specificity problems already. What about using .toolbar-pf-view-selector:last-child {border-right: 0px;} instead?

**Comment by jeff-phillips-18** [comment]
Seems to me setting it on the last-child makes more sense anyhow. If there is no view selector, then there should be no right border on the find group either. So, .toolbar-pf-actions-right:last-child{border-right: 0px;}

I would say the same would hold true for the toolbar in general so also .toolbar-pf-actions:last-child{border-right: 0px;}

@LHinson Do you agree that there should be no vertical bar to the right when there is no more following content?

**Comment by LHinson** [comment]
Yes agreed @jeff-phillips-18

**Comment by junezhang** [comment]
Okay, Thanks all for your kind suggestions. I will close it and re-submit a new one.

**Pull request closed without merging**
